<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="simple_robot">

    <xacro:include filename="colors.xacro"/>

    <xacro:property name="box_side" value="0.4"/>
    <xacro:property name="wheel_radius" value="0.07"/>
    <xacro:property name="wheel_thickness" value="0.05"/>
    <xacro:property name="wheel_offset" value="0.07"/>
    <xacro:property name="lidar" value="0.05"/>

    <link name="world"></link>

    <!-- Base -->
    <joint name="base_joint" type="fixed">
        <origin xyz="1 1 0" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="base_link"/>
    </joint>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${box_side} ${box_side} ${box_side/2}"/>
            </geometry>
            <material name="red"/>
            <origin xyz="0 0 ${box_side/4 + wheel_radius}" rpy="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <box size="${box_side} ${box_side} ${box_side/2}"/>
            </geometry>
            <origin xyz="0 0 ${box_side/4 + wheel_radius}" rpy="0 0 0"/>
        </collision>
        <inertial>
            <origin xyz="0 0 ${box_side/4 + wheel_radius}" rpy="0 0 0"/>
            <mass value="10"/>
            <inertia ixx="1.6" ixy="0" ixz="1.6" iyy="1.6" iyz="1.6" izz="1.6"/>
        </inertial>
    </link>

    <!-- Macro to define a wheel -->
<xacro:macro name="wheel" params="name x y z ry vy roll">
  <joint name="${name}_joint" type="continuous">
    <parent link="base_link"/>
    <child link="${name}_link"/>
    <origin xyz="${x} ${y} ${z}" rpy="${roll} 0 0"/>
    <axis xyz="0 ${ry} 0"/>
  </joint>

  <link name="${name}_link">
    <visual>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
      <material name="blue"/>
      <origin xyz="0 ${vy} 0" rpy="1.57 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
      <origin xyz="0 ${vy} 0" rpy="1.57 0 0"/>
    </collision>
    <inertial>
      <origin xyz="0 ${vy} 0"/>
      <mass value="1"/>
      <inertia ixx="0.002" iyy="0.002" izz="0.0025" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>
</xacro:macro>


<!-- Front Right -->
<xacro:wheel name="wheel_fr" x="${ box_side/2 - wheel_offset}" y="${-box_side/2}" 
z="${wheel_radius}" ry="${1}" vy="${-wheel_thickness/2}" roll="${0}"/>

<!-- Front Left -->
<xacro:wheel name="wheel_fl" x="${ box_side/2 - wheel_offset}" y="${ box_side/2}" 
z="${wheel_radius}" ry="${-1}" vy="${-wheel_thickness/2}" roll="${3.14}"/>

<!-- Back Right -->
<xacro:wheel name="wheel_br" x="${-box_side/2 + wheel_offset}" y="${-box_side/2}" 
z="${wheel_radius}" ry="${1}" vy="${-wheel_thickness/2}" roll="${0}"/>

<!-- Back Left -->
<xacro:wheel name="wheel_bl" x="${-box_side/2 + wheel_offset}" y="${ box_side/2}" 
z="${wheel_radius}" ry="${-1}" vy="${-wheel_thickness/2}" roll="${3.14}"/>


         <!-- === LiDAR === -->
    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <!-- Place LiDAR above the base box -->
        <origin xyz="0 0 ${box_side/2 + wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="lidar_link">
  <!-- visual: use LDS mesh -->
  <visual>
    <geometry>
      <mesh filename="package://turtlebot3_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <origin xyz="0 0 0.022" rpy="0 0 0"/>
    <material name="blue"/>
  </visual>

  <!-- collision: keep a simple cylinder -->
  <collision>
    <geometry>
      <cylinder length="0.05" radius="0.03"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </collision>

  <!-- inertia -->
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <mass value="0.1"/>
    <inertia ixx="0.00017" iyy="0.00017" izz="0.000125" ixy="0" ixz="0" iyz="0"/>
  </inertial>
</link>

</robot>
